-- Smart Gym AI System Database Schema
-- Create Database
CREATE DATABASE IF NOT EXISTS smart_gym;
USE smart_gym;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('Athlete', 'Coach', 'Admin') NOT NULL DEFAULT 'Athlete',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. SensorData Table (Streaming simulation)
CREATE TABLE IF NOT EXISTS SensorData (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    heart_rate INT NOT NULL,
    steps INT NOT NULL,
    calories INT NOT NULL,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- 3. AI_Predictions Table
CREATE TABLE IF NOT EXISTS AI_Predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    fatigue_level DECIMAL(5,2) NOT NULL, -- e.g., 68.50 for 68.5%
    injury_risk DECIMAL(5,2) NOT NULL,   -- e.g., 14.00 for 14%
    prediction_details TEXT,
    prediction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- 4. TrainingPlans Table
CREATE TABLE IF NOT EXISTS TrainingPlans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    coach_id INT DEFAULT NULL, -- NULL if generated by AI
    plan_type ENUM('AI-Generated', 'Manual') NOT NULL,
    plan_details JSON NOT NULL, -- structured plan data
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (coach_id) REFERENCES Users(id) ON DELETE SET NULL
);

-- 5. PerformanceMetrics Table
CREATE TABLE IF NOT EXISTS PerformanceMetrics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    activity_type VARCHAR(100) NOT NULL,
    duration_min INT NOT NULL,
    avg_heart_rate INT NOT NULL,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- Insert Dummy Users (Passwords are plain format for demo purposes, normally should be hashed with bcrypt)
INSERT INTO Users (name, email, password, role) VALUES 
('فيصل', 'admin@smartgym.ai', '1234', 'Admin'),
('محمد', 'coach@smartgym.ai', '1234', 'Coach'),
('نواف', 'omar@smartgym.ai', '1234', 'Athlete')
ON DUPLICATE KEY UPDATE id=id;
